- name: groups | render template groups.ldif
  template:
    src: templates/groups.ldif.j2
    dest: "{{ tmp_dir }}/groups.ldif"

- name: groups | add config
  command: "ldapadd -cxD cn=admin,{{ ldap_basedc }} -w {{ ldap_pw }} -f {{ tmp_dir }}/groups.ldif"
